---
title: "DeepLili Stats"
output: html_notebook
---



```{r}
# Set the working directory to where the directories are located
setwd("/home/harpo/Dropbox/deeplili/")

# List directories in the specified path
directories <- list.dirs(path = ".", full.names = FALSE, recursive = FALSE)

# Convert directory names to Date objects assuming they are in 'YYYY-MM-DD' format
date_directories <- as.Date(directories, format = "%Y-%m-%d")
```



```{r}
# Load required libraries
library(ggplot2)
library(hrbrthemes)

# Create a data frame for plotting
date_data <- data.frame(dates = date_directories)

# Create and print the histogram
ggplot(date_data, aes(y = dates)) +
  geom_histogram(binwidth = 1, color = "black", fill = "green", aes(x = ..count..)) +
  geom_text(stat = 'count', aes(label = ..count..), hjust = -0.1) +  # Add count labels
  ggdark::dark_theme_classic()+
  labs(title = "DeepLili MMAMM 2024", subtitle = "Per day activity", x = "Date", y = "Frequency")


ggsave("deeplili_stas.png",width = 14,height = 5,units = 'in')
```

```{r}
getwd()
```


